apiVersion: v1
kind: Service
metadata:
  name: gitops-demo-app
  namespace: argocd-test
  labels:
    app.kubernetes.io/name: gitops-demo-app
    app.kubernetes.io/part-of: gitops-lab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gitops-demo-app
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP

